// ai_image_recognition_frontend/src/views/EvaluationOptimization.vue
<template>
  <div class="evaluation-page">
    <el-card class="header-card">
      <div class="header-top">
        <div>
          <h1 class="page-title">评估优化</h1>
          <div class="page-subtitle">从训练产物一键评估，并沉淀评估记录用于后续优化迭代</div>
        </div>
        <div class="header-actions">
          <el-button @click="refreshAll" :loading="loadingAny">刷新</el-button>
        </div>
      </div>
      <div class="project-line">
        <span class="label">当前项目</span>
        <el-tag v-if="currentProject" type="success">{{ currentProject.name }} ({{ currentProject.id }})</el-tag>
        <el-tag v-else type="info">未选择</el-tag>
      </div>
      <el-alert
        v-if="!currentProject"
        type="warning"
        show-icon
        title="未选择项目"
        description="请先在首页创建/选择项目，再进入评估优化。"
        style="margin-top: 12px;"
      />
    </el-card>

    <el-tabs v-model="activeTab" class="main-tabs">
      <el-tab-pane label="一键评估" name="run">
        <el-row :gutter="16">
          <el-col :span="10">
            <el-card class="panel-card">
              <template #header>
                <div class="card-header">
                  <span>评估输入</span>
                  <el-button type="primary" plain @click="loadLatestEvaluationData" :disabled="!currentProject" :loading="loadingEvalData">
                    从最新训练产物加载
                  </el-button>
                </div>
              </template>

              <el-form label-width="110px">
                <el-form-item label="IOU 阈值">
                  <el-slider v-model="iouThreshold" :min="0.3" :max="0.9" :step="0.05" show-input />
                </el-form-item>
              </el-form>

              <div v-if="evaluationData" class="data-summary">
                <el-descriptions :column="1" border size="small">
                  <el-descriptions-item label="model_id">{{ evaluationData.model_id || '未知' }}</el-descriptions-item>
                  <el-descriptions-item label="task_id">{{ evaluationData.task_id || '未知' }}</el-descriptions-item>
                  <el-descriptions-item label="predictions">{{ evaluationData.predictions?.length || 0 }}</el-descriptions-item>
                  <el-descriptions-item label="ground_truths">{{ evaluationData.ground_truths?.length || 0 }}</el-descriptions-item>
                </el-descriptions>
                <el-alert
                  v-if="(evaluationData.ground_truths?.length || 0) === 0"
                  type="warning"
                  show-icon
                  title="ground_truths 为 0"
                  description="这会导致评估结果全部为 0。通常原因是：验证集划分到了未标注图片，或 labels/val 下的 txt 为空。请回到“图像标注 → 导入到项目”，确保验证集图片有标注。"
                  style="margin-top: 10px;"
                />
              </div>
              <el-empty v-else description="未加载评估数据" :image-size="90" />

              <div style="margin-top: 14px; display: flex; justify-content: flex-end;">
                <el-button
                  type="primary"
                  @click="startEvaluation"
                  :disabled="!canStartEvaluation"
                  :loading="loadingEvaluation"
                >
                  {{ loadingEvaluation ? '评估中...' : '开始评估' }}
                </el-button>
              </div>
            </el-card>

            <el-card class="panel-card" style="margin-top: 16px;">
              <template #header>
                <div class="card-header">
                  <span>评估日志</span>
                  <el-tag v-if="polling" type="warning">轮询中</el-tag>
                </div>
              </template>
              <el-empty v-if="!evaluationResult" description="暂无评估任务" :image-size="80" />
              <div v-else class="log-box">
                <div class="log-line"><span class="k">evaluation_id</span><span class="v">{{ evaluationResult.evaluation_id }}</span></div>
                <div class="log-line"><span class="k">status</span><span class="v">{{ evaluationResult.status }}</span></div>
                <div class="log-line" v-if="evaluationResult.error_message"><span class="k">error</span><span class="v danger">{{ evaluationResult.error_message }}</span></div>
              </div>
            </el-card>
          </el-col>

          <el-col :span="14">
            <el-card class="panel-card">
              <template #header>
                <div class="card-header">
                  <span>评估结果</span>
                  <el-tag v-if="evaluationResult?.status" :type="statusTagType">{{ statusLabel }}</el-tag>
                </div>
              </template>

              <el-empty v-if="!evaluationResult" description="暂无评估结果" :image-size="120" />

              <div v-else>
                <el-alert
                  v-if="evaluationResult.status === 'failed'"
                  type="error"
                  show-icon
                  title="评估失败"
                  :description="evaluationResult.error_message || '未知错误'"
                  style="margin-bottom: 12px;"
                />

                <div v-if="evaluationResult.status === 'completed'">
                  <el-row :gutter="12" style="margin-bottom: 12px;">
                    <el-col :span="6"><el-card class="metric-card"><div class="metric-k">mAP@0.5</div><div class="metric-v">{{ fmtNum(evaluationResult.metrics?.mAP50) }}</div></el-card></el-col>
                    <el-col :span="6"><el-card class="metric-card"><div class="metric-k">mAP@0.5:0.95</div><div class="metric-v">{{ fmtNum(evaluationResult.metrics?.mAP50_95) }}</div></el-card></el-col>
                    <el-col :span="6"><el-card class="metric-card"><div class="metric-k">Precision</div><div class="metric-v">{{ fmtNum(evaluationResult.metrics?.precision) }}</div></el-card></el-col>
                    <el-col :span="6"><el-card class="metric-card"><div class="metric-k">Recall</div><div class="metric-v">{{ fmtNum(evaluationResult.metrics?.recall) }}</div></el-card></el-col>
                  </el-row>

                  <el-divider content-position="left">PR 曲线</el-divider>
                  <div v-if="prCurveImage" class="pr-image-wrap">
                    <img :src="prCurveImage" alt="PR Curve" />
                  </div>
                  <el-empty v-else description="暂无 PR 曲线" :image-size="70" />

                  <el-divider content-position="left">分类别指标</el-divider>
                  <el-table :data="classMetricRows" height="240" style="width: 100%;">
                    <el-table-column prop="className" label="类别" min-width="160" />
                    <el-table-column prop="precision" label="Precision" width="120" />
                    <el-table-column prop="recall" label="Recall" width="120" />
                    <el-table-column prop="f1" label="F1" width="120" />
                    <el-table-column prop="ap" label="AP" width="120" />
                  </el-table>

                  <el-divider content-position="left">优化建议</el-divider>
                  <el-input
                    type="textarea"
                    :rows="10"
                    readonly
                    :model-value="evaluationResult.llm_analysis || ''"
                    placeholder="暂无分析报告"
                  />
                </div>
              </div>
            </el-card>
          </el-col>
        </el-row>
      </el-tab-pane>

      <el-tab-pane label="历史评估" name="history">
        <el-card class="panel-card">
          <template #header>
            <div class="card-header">
              <span>项目评估记录</span>
              <el-button @click="refreshHistory" :disabled="!currentProject" :loading="loadingHistory">刷新列表</el-button>
            </div>
          </template>

          <el-empty v-if="!currentProject" description="未选择项目" :image-size="90" />

          <div v-else>
            <el-table
              :data="projectEvaluations"
              style="width: 100%;"
              height="340"
              @row-click="selectHistoryRow"
            >
              <el-table-column prop="evaluation_id" label="evaluation_id" min-width="220" />
              <el-table-column prop="created_at" label="创建时间" min-width="180" />
              <el-table-column label="mAP50" width="120">
                <template #default="{ row }">{{ fmtNum(row.summary?.mAP50) }}</template>
              </el-table-column>
              <el-table-column label="mAP50_95" width="120">
                <template #default="{ row }">{{ fmtNum(row.summary?.mAP50_95) }}</template>
              </el-table-column>
              <el-table-column label="操作" width="120">
                <template #default="{ row }">
                  <el-button size="small" @click.stop="loadHistoryDetail(row.evaluation_id)">查看</el-button>
                </template>
              </el-table-column>
            </el-table>

            <el-divider content-position="left">详情</el-divider>
            <el-empty v-if="!historyDetail" description="点击上方记录查看详情" :image-size="90" />
            <div v-else>
              <el-row :gutter="12" style="margin-bottom: 12px;">
                <el-col :span="6"><el-card class="metric-card"><div class="metric-k">mAP@0.5</div><div class="metric-v">{{ fmtNum(historyDetail.metrics?.mAP50) }}</div></el-card></el-col>
                <el-col :span="6"><el-card class="metric-card"><div class="metric-k">mAP@0.5:0.95</div><div class="metric-v">{{ fmtNum(historyDetail.metrics?.mAP50_95) }}</div></el-card></el-col>
                <el-col :span="6"><el-card class="metric-card"><div class="metric-k">Precision</div><div class="metric-v">{{ fmtNum(historyDetail.metrics?.precision) }}</div></el-card></el-col>
                <el-col :span="6"><el-card class="metric-card"><div class="metric-k">Recall</div><div class="metric-v">{{ fmtNum(historyDetail.metrics?.recall) }}</div></el-card></el-col>
              </el-row>

              <el-input
                type="textarea"
                :rows="14"
                readonly
                :model-value="historyDetail.report_md || ''"
                placeholder="暂无报告"
              />
            </div>
          </div>
        </el-card>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { evaluationAPI } from '@/api/evaluation.js';
import { getCurrentProject } from '@/utils/projectManager.js';

const activeTab = ref('run');
const currentProject = ref(getCurrentProject());

const iouThreshold = ref(0.5);
const evaluationData = ref(null);
const evaluationResult = ref(null);

const loadingEvalData = ref(false);
const loadingEvaluation = ref(false);
const loadingHistory = ref(false);

const projectEvaluations = ref([]);
const historyDetail = ref(null);

const polling = ref(false);
const pollingTimer = ref(null);
const pollingAttempts = ref(0);
const maxPollingAttempts = 60;

const loadingAny = computed(() => loadingEvalData.value || loadingEvaluation.value || loadingHistory.value);

const canStartEvaluation = computed(() => {
  const preds = evaluationData.value?.predictions;
  const gts = evaluationData.value?.ground_truths;
  return (
    !!currentProject.value?.id &&
    !!evaluationData.value?.model_id &&
    Array.isArray(preds) &&
    Array.isArray(gts) &&
    preds.length > 0 &&
    gts.length > 0
  );
});

const prCurveImage = computed(() => {
  const raw = evaluationResult.value?.pr_curve_image;
  if (!raw) return null;
  return `data:image/png;base64,${raw}`;
});

const statusLabel = computed(() => {
  const s = evaluationResult.value?.status;
  if (s === 'pending') return '等待中';
  if (s === 'running') return '运行中';
  if (s === 'completed') return '已完成';
  if (s === 'failed') return '失败';
  return s || '未知';
});

const statusTagType = computed(() => {
  const s = evaluationResult.value?.status;
  if (s === 'completed') return 'success';
  if (s === 'failed') return 'danger';
  if (s === 'running') return 'warning';
  return 'info';
});

const classMetricRows = computed(() => {
  const classMetrics = evaluationResult.value?.metrics?.class_metrics || {};
  const rows = [];
  for (const [className, m] of Object.entries(classMetrics)) {
    rows.push({
      className,
      precision: fmtNum(m?.precision),
      recall: fmtNum(m?.recall),
      f1: fmtNum(m?.f1_score),
      ap: fmtNum(m?.ap),
    });
  }
  rows.sort((a, b) => String(a.className).localeCompare(String(b.className)));
  return rows;
});

function fmtNum(v) {
  const n = Number(v);
  if (!Number.isFinite(n)) return '-';
  return n.toFixed(4);
}

function stopPolling() {
  if (pollingTimer.value) {
    clearInterval(pollingTimer.value);
    pollingTimer.value = null;
  }
  polling.value = false;
  pollingAttempts.value = 0;
}

async function pollResult(evaluationId, modelId) {
  stopPolling();
  polling.value = true;
  pollingTimer.value = setInterval(async () => {
    try {
      pollingAttempts.value += 1;
      if (pollingAttempts.value > maxPollingAttempts) {
        stopPolling();
        loadingEvaluation.value = false;
        ElMessage.warning('评估轮询超时，请稍后在历史记录中查看');
        return;
      }
      const resp = await evaluationAPI.getEvaluationResult(evaluationId, modelId);
      evaluationResult.value = resp.data;
      if (['completed', 'failed'].includes(resp.data.status)) {
        stopPolling();
        loadingEvaluation.value = false;
        refreshHistory();
      }
    } catch (e) {
      console.error('轮询评估结果失败:', e);
      stopPolling();
      loadingEvaluation.value = false;
      ElMessage.error('获取评估结果失败');
    }
  }, 2000);
}

async function loadLatestEvaluationData() {
  currentProject.value = getCurrentProject();
  if (!currentProject.value?.id) {
    ElMessage.warning('请先在首页创建/选择项目');
    return;
  }
  loadingEvalData.value = true;
  try {
    const resp = await evaluationAPI.getLatestEvaluationData(currentProject.value.id);
    evaluationData.value = resp.data?.data || null;
    if (!evaluationData.value) {
      ElMessage.warning('未找到可用的 evaluation_data.json');
    } else {
      ElMessage.success('已加载最新训练产物的评估数据');
    }
  } catch (e) {
    console.error('加载评估数据失败:', e);
    ElMessage.error('加载评估数据失败: ' + (e.response?.data?.detail || e.message));
  } finally {
    loadingEvalData.value = false;
  }
}

async function startEvaluation() {
  currentProject.value = getCurrentProject();
  if (!canStartEvaluation.value) {
    const preds = evaluationData.value?.predictions;
    const gts = evaluationData.value?.ground_truths;
    if (!Array.isArray(preds) || preds.length === 0) {
      ElMessage.warning('评估数据不完整：predictions 为空');
      return;
    }
    if (!Array.isArray(gts) || gts.length === 0) {
      ElMessage.warning('评估数据不完整：ground_truths 为空（验证集标签可能缺失或为空）');
      return;
    }
    ElMessage.warning('请先加载评估数据');
    return;
  }
  loadingEvaluation.value = true;
  evaluationResult.value = null;
  try {
    const payload = {
      model_id: evaluationData.value.model_id,
      task_id: evaluationData.value.task_id || null,
      project_id: currentProject.value.id,
      iou_threshold: Number(iouThreshold.value || 0.5),
      predictions: evaluationData.value.predictions,
      ground_truths: evaluationData.value.ground_truths,
    };
    const resp = await evaluationAPI.startEvaluation(evaluationData.value.model_id, payload);
    const evaluationId = resp.data?.evaluation_id;
    if (!evaluationId) {
      throw new Error('后端未返回 evaluation_id');
    }
    await pollResult(evaluationId, evaluationData.value.model_id);
  } catch (e) {
    console.error('启动评估失败:', e);
    loadingEvaluation.value = false;
    ElMessage.error('启动评估失败: ' + (e.response?.data?.detail || e.message));
  }
}

async function refreshHistory() {
  currentProject.value = getCurrentProject();
  if (!currentProject.value?.id) return;
  loadingHistory.value = true;
  try {
    const resp = await evaluationAPI.listProjectEvaluations(currentProject.value.id, 80);
    projectEvaluations.value = resp.data?.evaluations || [];
  } catch (e) {
    console.error('刷新历史评估失败:', e);
    ElMessage.error('刷新历史评估失败: ' + (e.response?.data?.detail || e.message));
  } finally {
    loadingHistory.value = false;
  }
}

async function loadHistoryDetail(evaluationId) {
  currentProject.value = getCurrentProject();
  if (!currentProject.value?.id) return;
  loadingHistory.value = true;
  try {
    const resp = await evaluationAPI.getProjectEvaluation(currentProject.value.id, evaluationId);
    historyDetail.value = resp.data || null;
  } catch (e) {
    console.error('加载评估详情失败:', e);
    ElMessage.error('加载评估详情失败: ' + (e.response?.data?.detail || e.message));
  } finally {
    loadingHistory.value = false;
  }
}

function selectHistoryRow(row) {
  if (!row?.evaluation_id) return;
  loadHistoryDetail(row.evaluation_id);
}

async function refreshAll() {
  currentProject.value = getCurrentProject();
  await refreshHistory();
}

onMounted(() => {
  refreshAll();
});

onUnmounted(() => {
  stopPolling();
});
</script>

<style scoped>
.evaluation-page {
  padding: 20px;
}

.header-card {
  margin-bottom: 16px;
}

.header-top {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 12px;
}

.page-title {
  margin: 0;
  font-size: 22px;
  font-weight: 700;
  color: #303133;
}

.page-subtitle {
  margin-top: 6px;
  color: #909399;
  font-size: 13px;
}

.project-line {
  margin-top: 12px;
  display: flex;
  align-items: center;
  gap: 10px;
}

.project-line .label {
  color: #606266;
  font-size: 13px;
}

.main-tabs {
  margin-top: 10px;
}

.panel-card {
  border-radius: 10px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 10px;
}

.data-summary {
  margin-top: 12px;
}

.metric-card {
  border-radius: 10px;
}

.metric-k {
  color: #909399;
  font-size: 12px;
}

.metric-v {
  margin-top: 6px;
  font-size: 20px;
  font-weight: 700;
  color: #303133;
}

.pr-image-wrap {
  width: 100%;
  overflow: hidden;
  border: 1px solid #ebeef5;
  border-radius: 10px;
  background: #fff;
}

.pr-image-wrap img {
  width: 100%;
  display: block;
}

.log-box {
  padding: 10px 12px;
  background: #f5f7fa;
  border-radius: 10px;
  border: 1px solid #ebeef5;
}

.log-line {
  display: flex;
  gap: 10px;
  padding: 4px 0;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
  font-size: 12px;
}

.log-line .k {
  width: 110px;
  color: #606266;
}

.log-line .v {
  color: #303133;
}

.log-line .v.danger {
  color: #f56c6c;
}
</style>

// ai_image_recognition_frontend/src/app/evaluation-optimization/page.jsx
"use client";

import { Alert, Button, Card, Descriptions, Empty, Input, Slider, Table, Tabs, Tag, Typography, message } from "antd";
import { useEffect, useMemo, useRef, useState } from "react";
import { evaluationAPI } from "@/api/evaluation";
import { getCurrentProject } from "@/lib/projectManager";

function fmtNum(v) {
  const n = Number(v);
  if (!Number.isFinite(n)) return "-";
  return n.toFixed(4);
}

export default function EvaluationOptimizationPage() {
  const [activeTab, setActiveTab] = useState("run");
  const [currentProject, setCurrentProject] = useState(null);

  const [iouThreshold, setIouThreshold] = useState(0.5);
  const [evaluationData, setEvaluationData] = useState(null);
  const [evaluationResult, setEvaluationResult] = useState(null);

  const [loadingEvalData, setLoadingEvalData] = useState(false);
  const [loadingEvaluation, setLoadingEvaluation] = useState(false);
  const [loadingHistory, setLoadingHistory] = useState(false);

  const [projectEvaluations, setProjectEvaluations] = useState([]);
  const [historyDetail, setHistoryDetail] = useState(null);

  const pollingTimerRef = useRef(null);
  const pollingAttemptsRef = useRef(0);
  const maxPollingAttempts = 60;

  const loadingAny = loadingEvalData || loadingEvaluation || loadingHistory;

  const canStartEvaluation = useMemo(() => {
    const preds = evaluationData?.predictions;
    const gts = evaluationData?.ground_truths;
    return !!currentProject?.id && !!evaluationData?.model_id && Array.isArray(preds) && Array.isArray(gts) && preds.length > 0 && gts.length > 0;
  }, [currentProject?.id, evaluationData]);

  const prCurveImage = useMemo(() => {
    const raw = evaluationResult?.pr_curve_image;
    if (!raw) return null;
    return `data:image/png;base64,${raw}`;
  }, [evaluationResult]);

  const statusLabel = useMemo(() => {
    const s = evaluationResult?.status;
    if (s === "pending") return "等待中";
    if (s === "running") return "运行中";
    if (s === "completed") return "已完成";
    if (s === "failed") return "失败";
    return s || "未知";
  }, [evaluationResult?.status]);

  const statusTagColor = useMemo(() => {
    const s = evaluationResult?.status;
    if (s === "completed") return "green";
    if (s === "failed") return "red";
    if (s === "running") return "orange";
    return "default";
  }, [evaluationResult?.status]);

  const classMetricRows = useMemo(() => {
    const classMetrics = evaluationResult?.metrics?.class_metrics || {};
    const rows = Object.entries(classMetrics).map(([className, m]) => ({
      className,
      precision: fmtNum(m?.precision),
      recall: fmtNum(m?.recall),
      f1: fmtNum(m?.f1_score),
      ap: fmtNum(m?.ap),
    }));
    rows.sort((a, b) => String(a.className).localeCompare(String(b.className)));
    return rows;
  }, [evaluationResult]);

  const stopPolling = () => {
    if (pollingTimerRef.current) {
      clearInterval(pollingTimerRef.current);
      pollingTimerRef.current = null;
    }
    pollingAttemptsRef.current = 0;
  };

  const pollResult = async (evaluationId, modelId) => {
    stopPolling();
    pollingTimerRef.current = setInterval(async () => {
      try {
        pollingAttemptsRef.current += 1;
        if (pollingAttemptsRef.current > maxPollingAttempts) {
          stopPolling();
          setLoadingEvaluation(false);
          message.warning("评估轮询超时，请稍后在历史记录中查看");
          return;
        }
        const resp = await evaluationAPI.getEvaluationResult(evaluationId, modelId);
        setEvaluationResult(resp.data);
        if (["completed", "failed"].includes(resp.data?.status)) {
          stopPolling();
          setLoadingEvaluation(false);
          refreshHistory();
        }
      } catch (e) {
        stopPolling();
        setLoadingEvaluation(false);
        message.error("获取评估结果失败");
      }
    }, 2000);
  };

  const loadLatestEvaluationData = async () => {
    const proj = getCurrentProject();
    setCurrentProject(proj);
    if (!proj?.id) {
      message.warning("请先在首页创建/选择项目");
      return;
    }
    setLoadingEvalData(true);
    try {
      const resp = await evaluationAPI.getLatestEvaluationData(proj.id);
      const data = resp.data?.data || null;
      setEvaluationData(data);
      if (!data) message.warning("未找到可用的 evaluation_data.json");
      else message.success("已加载最新训练产物的评估数据");
    } catch (e) {
      message.error(`加载评估数据失败：${e?.response?.data?.detail || e.message}`);
    } finally {
      setLoadingEvalData(false);
    }
  };

  const startEvaluation = async () => {
    const proj = getCurrentProject();
    setCurrentProject(proj);
    if (!canStartEvaluation) {
      const preds = evaluationData?.predictions;
      const gts = evaluationData?.ground_truths;
      if (!Array.isArray(preds) || preds.length === 0) {
        message.warning("评估数据不完整：predictions 为空");
        return;
      }
      if (!Array.isArray(gts) || gts.length === 0) {
        message.warning("评估数据不完整：ground_truths 为空（验证集标签可能缺失或为空）");
        return;
      }
      message.warning("请先加载评估数据");
      return;
    }
    setLoadingEvaluation(true);
    setEvaluationResult(null);
    try {
      const payload = {
        model_id: evaluationData.model_id,
        task_id: evaluationData.task_id || null,
        project_id: proj.id,
        iou_threshold: Number(iouThreshold || 0.5),
        predictions: evaluationData.predictions,
        ground_truths: evaluationData.ground_truths,
      };
      const resp = await evaluationAPI.startEvaluation(evaluationData.model_id, payload);
      const evaluationId = resp.data?.evaluation_id;
      if (!evaluationId) throw new Error("后端未返回 evaluation_id");
      await pollResult(evaluationId, evaluationData.model_id);
    } catch (e) {
      setLoadingEvaluation(false);
      message.error(`启动评估失败：${e?.response?.data?.detail || e.message}`);
    }
  };

  const refreshHistory = async () => {
    const proj = getCurrentProject();
    setCurrentProject(proj);
    if (!proj?.id) return;
    setLoadingHistory(true);
    try {
      const resp = await evaluationAPI.listProjectEvaluations(proj.id, 80);
      setProjectEvaluations(resp.data?.evaluations || []);
    } catch (e) {
      message.error(`刷新历史评估失败：${e?.response?.data?.detail || e.message}`);
    } finally {
      setLoadingHistory(false);
    }
  };

  const loadHistoryDetail = async (evaluationId) => {
    const proj = getCurrentProject();
    setCurrentProject(proj);
    if (!proj?.id) return;
    setLoadingHistory(true);
    try {
      const resp = await evaluationAPI.getProjectEvaluation(proj.id, evaluationId);
      setHistoryDetail(resp.data || null);
    } catch (e) {
      message.error(`加载评估详情失败：${e?.response?.data?.detail || e.message}`);
    } finally {
      setLoadingHistory(false);
    }
  };

  const refreshAll = async () => {
    setCurrentProject(getCurrentProject());
    await refreshHistory();
  };

  useEffect(() => {
    refreshAll();
    return () => stopPolling();
  }, []);

  return (
    <div className="app-page">
      <Card className="app-card" style={{ marginBottom: 14 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 }}>
          <div>
            <Typography.Title level={3} style={{ margin: 0 }}>
              评估优化
            </Typography.Title>
            <div style={{ marginTop: 6, color: "rgba(15,23,42,0.65)" }}>从训练产物一键评估，并沉淀评估记录用于后续优化迭代</div>
          </div>
          <Button onClick={refreshAll} loading={loadingAny}>
            刷新
          </Button>
        </div>
        <div style={{ marginTop: 10, display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ color: "rgba(15,23,42,0.65)" }}>当前项目</span>
          {currentProject?.id ? <Tag color="green">{currentProject.name} ({currentProject.id})</Tag> : <Tag>未选择</Tag>}
        </div>
        {!currentProject?.id ? (
          <Alert style={{ marginTop: 10 }} type="warning" showIcon title="未选择项目" description="请先在首页创建/选择项目，再进入评估优化。" />
        ) : null}
      </Card>

      <Tabs
        activeKey={activeTab}
        onChange={setActiveTab}
        items={[
          {
            key: "run",
            label: "一键评估",
            children: (
              <div style={{ display: "grid", gridTemplateColumns: "10fr 14fr", gap: 14 }}>
                <div style={{ display: "grid", gap: 14 }}>
                  <Card
                    className="app-card"
                    title={
                      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 }}>
                        <span style={{ fontWeight: 800 }}>评估输入</span>
                        <Button type="primary" ghost onClick={loadLatestEvaluationData} disabled={!currentProject?.id} loading={loadingEvalData}>
                          从最新训练产物加载
                        </Button>
                      </div>
                    }
                  >
                    <div style={{ marginBottom: 10 }}>
                      <div style={{ marginBottom: 6, color: "rgba(15,23,42,0.65)" }}>IOU 阈值</div>
                      <Slider min={0.3} max={0.9} step={0.05} value={iouThreshold} onChange={setIouThreshold} />
                    </div>

                    {evaluationData ? (
                      <>
                        <Descriptions column={1} bordered size="small">
                          <Descriptions.Item label="model_id">{evaluationData.model_id || "未知"}</Descriptions.Item>
                          <Descriptions.Item label="task_id">{evaluationData.task_id || "未知"}</Descriptions.Item>
                          <Descriptions.Item label="predictions">{evaluationData.predictions?.length || 0}</Descriptions.Item>
                          <Descriptions.Item label="ground_truths">{evaluationData.ground_truths?.length || 0}</Descriptions.Item>
                        </Descriptions>
                        {(evaluationData.ground_truths?.length || 0) === 0 ? (
                          <Alert
                            style={{ marginTop: 10 }}
                            type="warning"
                            showIcon
                            title="ground_truths 为 0"
                            description="这会导致评估结果全部为 0。通常原因是：验证集划分到了未标注图片，或 labels/val 下的 txt 为空。请回到“图像标注 → 导入到项目”，确保验证集图片有标注。"
                          />
                        ) : null}
                      </>
                    ) : (
                      <Empty description="未加载评估数据" />
                    )}

                    <div style={{ marginTop: 12, display: "flex", justifyContent: "flex-end" }}>
                      <Button type="primary" onClick={startEvaluation} disabled={!canStartEvaluation} loading={loadingEvaluation}>
                        {loadingEvaluation ? "评估中..." : "开始评估"}
                      </Button>
                    </div>
                  </Card>

                  <Card className="app-card" title={<span style={{ fontWeight: 800 }}>评估日志</span>}>
                    {!evaluationResult ? (
                      <Empty description="暂无评估任务" />
                    ) : (
                      <div style={{ display: "grid", gap: 8 }}>
                        <div><b>evaluation_id</b>：{evaluationResult.evaluation_id}</div>
                        <div><b>status</b>：{evaluationResult.status}</div>
                        {evaluationResult.error_message ? <div style={{ color: "#cf1322" }}><b>error</b>：{evaluationResult.error_message}</div> : null}
                      </div>
                    )}
                  </Card>
                </div>

                <Card
                  className="app-card"
                  title={
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                      <span style={{ fontWeight: 800 }}>评估结果</span>
                      {evaluationResult?.status ? <Tag color={statusTagColor}>{statusLabel}</Tag> : null}
                    </div>
                  }
                >
                  {!evaluationResult ? (
                    <Empty description="暂无评估结果" />
                  ) : (
                    <>
                      {evaluationResult.status === "failed" ? (
                        <Alert style={{ marginBottom: 10 }} type="error" showIcon title="评估失败" description={evaluationResult.error_message || "未知错误"} />
                      ) : null}

                      {evaluationResult.status === "completed" ? (
                        <>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 10 }}>
                            <Card size="small" className="app-card"><div style={{ color: "rgba(15,23,42,0.65)" }}>mAP@0.5</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmtNum(evaluationResult.metrics?.mAP50)}</div></Card>
                            <Card size="small" className="app-card"><div style={{ color: "rgba(15,23,42,0.65)" }}>mAP@0.5:0.95</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmtNum(evaluationResult.metrics?.mAP50_95)}</div></Card>
                            <Card size="small" className="app-card"><div style={{ color: "rgba(15,23,42,0.65)" }}>Precision</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmtNum(evaluationResult.metrics?.precision)}</div></Card>
                            <Card size="small" className="app-card"><div style={{ color: "rgba(15,23,42,0.65)" }}>Recall</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmtNum(evaluationResult.metrics?.recall)}</div></Card>
                          </div>

                          <div style={{ marginTop: 14 }}>
                            <Typography.Title level={5} style={{ marginBottom: 8 }}>PR 曲线</Typography.Title>
                            {prCurveImage ? (
                              <div style={{ padding: 10, borderRadius: 12, border: "1px solid rgba(15,23,42,0.06)", background: "#fff" }}>
                                <img src={prCurveImage} alt="PR Curve" style={{ width: "100%", height: "auto" }} />
                              </div>
                            ) : (
                              <Empty description="暂无 PR 曲线" />
                            )}
                          </div>

                          <div style={{ marginTop: 14 }}>
                            <Typography.Title level={5} style={{ marginBottom: 8 }}>分类别指标</Typography.Title>
                            <Table
                              size="small"
                              rowKey={(r) => r.className}
                              dataSource={classMetricRows}
                              pagination={false}
                              scroll={{ y: 240 }}
                              columns={[
                                { title: "类别", dataIndex: "className", key: "className" },
                                { title: "Precision", dataIndex: "precision", key: "precision", width: 120 },
                                { title: "Recall", dataIndex: "recall", key: "recall", width: 120 },
                                { title: "F1", dataIndex: "f1", key: "f1", width: 120 },
                                { title: "AP", dataIndex: "ap", key: "ap", width: 120 },
                              ]}
                            />
                          </div>

                          <div style={{ marginTop: 14 }}>
                            <Typography.Title level={5} style={{ marginBottom: 8 }}>优化建议</Typography.Title>
                            <Input.TextArea rows={10} readOnly value={evaluationResult.llm_analysis || ""} placeholder="暂无分析报告" />
                          </div>
                        </>
                      ) : (
                        <Empty description="评估未完成" />
                      )}
                    </>
                  )}
                </Card>
              </div>
            ),
          },
          {
            key: "history",
            label: "历史评估",
            children: (
              <Card
                className="app-card"
                title={
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                    <span style={{ fontWeight: 800 }}>项目评估记录</span>
                    <Button onClick={refreshHistory} disabled={!currentProject?.id} loading={loadingHistory}>
                      刷新列表
                    </Button>
                  </div>
                }
              >
                {!currentProject?.id ? (
                  <Empty description="未选择项目" />
                ) : (
                  <>
                    <Table
                      rowKey={(r) => r.evaluation_id}
                      dataSource={projectEvaluations}
                      loading={loadingHistory}
                      size="small"
                      scroll={{ y: 340 }}
                      onRow={(row) => ({
                        onClick: () => loadHistoryDetail(row.evaluation_id),
                      })}
                      columns={[
                        { title: "evaluation_id", dataIndex: "evaluation_id", key: "evaluation_id", width: 240, ellipsis: true },
                        { title: "创建时间", dataIndex: "created_at", key: "created_at", width: 180 },
                        { title: "mAP50", key: "mAP50", width: 120, render: (_, row) => fmtNum(row.summary?.mAP50) },
                        { title: "mAP50_95", key: "mAP50_95", width: 120, render: (_, row) => fmtNum(row.summary?.mAP50_95) },
                        {
                          title: "操作",
                          key: "action",
                          width: 110,
                          render: (_, row) => (
                            <Button size="small" onClick={(e) => { e.stopPropagation(); loadHistoryDetail(row.evaluation_id); }}>
                              查看
                            </Button>
                          ),
                        },
                      ]}
                    />

                    <div style={{ marginTop: 12 }}>
                      <Typography.Title level={5} style={{ marginBottom: 8 }}>详情</Typography.Title>
                      {!historyDetail ? (
                        <Empty description="点击上方记录查看详情" />
                      ) : (
                        <>
                          <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 10, marginBottom: 10 }}>
                            <Card size="small" className="app-card"><div style={{ color: "rgba(15,23,42,0.65)" }}>mAP@0.5</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmtNum(historyDetail.metrics?.mAP50)}</div></Card>
                            <Card size="small" className="app-card"><div style={{ color: "rgba(15,23,42,0.65)" }}>mAP@0.5:0.95</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmtNum(historyDetail.metrics?.mAP50_95)}</div></Card>
                            <Card size="small" className="app-card"><div style={{ color: "rgba(15,23,42,0.65)" }}>Precision</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmtNum(historyDetail.metrics?.precision)}</div></Card>
                            <Card size="small" className="app-card"><div style={{ color: "rgba(15,23,42,0.65)" }}>Recall</div><div style={{ fontSize: 18, fontWeight: 800 }}>{fmtNum(historyDetail.metrics?.recall)}</div></Card>
                          </div>
                          <Input.TextArea rows={14} readOnly value={historyDetail.report_md || ""} placeholder="暂无报告" />
                        </>
                      )}
                    </div>
                  </>
                )}
              </Card>
            ),
          },
        ]}
      />
    </div>
  );
}
