// ai_image_recognition_frontend/src/views/Settings.vue
﻿<template>
  <div class="settings-page">
    <el-card class="header-card">
      <h1>系统设置</h1>
      <p>配置系统全局参数</p>
    </el-card>

    <el-card class="settings-form-card" style="margin-top: 20px;">
      <el-form :model="settings" label-width="150px" v-loading="loading">
        <el-form-item label="模型训练输出路径">
          <div style="display: flex; width: 100%; gap: 10px;">
            <el-input v-model="settings.training_output_path" placeholder="例如: runs/train" style="flex: 1;">
               <template #append>
                  <el-button :icon="Folder" @click="selectOutputFolder" title="选择文件夹" />
               </template>
            </el-input>
            <el-button type="primary" @click="saveSetting('training_output_path')">保存</el-button>
          </div>
          <div class="form-tip">指定模型训练结果（权重、日志等）的默认保存目录。支持绝对路径或相对路径。</div>
        </el-form-item>
        
      </el-form>
    </el-card>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { Folder } from '@element-plus/icons-vue'
import axios from 'axios'
import { getApiUrl } from '@/config/api.js'

const loading = ref(false)
const settings = reactive({
  training_output_path: ''
})

const selectOutputFolder = async () => {
  try {
    const response = await axios.get(`${getApiUrl()}/api/settings/select-path`)
    if (response.data.path) {
      settings.training_output_path = response.data.path
    }
  } catch (error) {
    console.error('选择路径失败:', error)
    ElMessage.error('无法打开文件夹选择器')
  }
}

const fetchSettings = async () => {
  loading.value = true
  try {
    const response = await axios.get(`${getApiUrl()}/api/settings/`)
    const data = response.data
    // Convert array to object for easier binding
    data.forEach(item => {
      // Allow dynamic keys or pre-defined keys
      settings[item.key] = item.value
    })
  } catch (error) {
    console.error('获取设置失败:', error)
    ElMessage.error('获取设置失败')
  } finally {
    loading.value = false
  }
}

const saveSetting = async (key) => {
  try {
    await axios.post(`${getApiUrl()}/api/settings/`, {
      key: key,
      value: settings[key],
      description: key === 'training_output_path' ? '模型训练结果输出路径' : ''
    })
    ElMessage.success('设置已保存')
  } catch (error) {
    console.error('保存设置失败:', error)
    ElMessage.error('保存设置失败')
  }
}

onMounted(() => {
  fetchSettings()
})
</script>

<style scoped>
.settings-page {
  padding: 20px;
}
.form-tip {
  font-size: 12px;
  color: #909399;
  margin-top: 4px;
}
</style>

// ai_image_recognition_frontend/src/app/settings/page.jsx
"use client";

import { Button, Card, Form, Input, Space, Typography, message } from "antd";
import { FolderOpenOutlined } from "@ant-design/icons";
import axios from "axios";
import { useEffect, useState } from "react";
import { getApiUrl } from "@/lib/api";

export default function SettingsPage() {
  const [loading, setLoading] = useState(false);
  const [form] = Form.useForm();

  const fetchSettings = async () => {
    setLoading(true);
    try {
      const resp = await axios.get(`${getApiUrl()}/api/settings/`);
      const list = Array.isArray(resp.data) ? resp.data : [];
      const next = {};
      for (const item of list) {
        if (!item?.key) continue;
        next[item.key] = item.value;
      }
      form.setFieldsValue(next);
    } catch {
      message.error("获取设置失败");
    } finally {
      setLoading(false);
    }
  };

  const selectOutputFolder = async () => {
    try {
      const resp = await axios.get(`${getApiUrl()}/api/settings/select-path`);
      if (resp.data?.path) {
        form.setFieldValue("training_output_path", resp.data.path);
      }
    } catch {
      message.error("无法打开文件夹选择器");
    }
  };

  const saveSetting = async (key) => {
    try {
      const value = form.getFieldValue(key);
      await axios.post(`${getApiUrl()}/api/settings/`, {
        key,
        value,
        description: key === "training_output_path" ? "模型训练结果输出路径" : "",
      });
      message.success("设置已保存");
    } catch {
      message.error("保存设置失败");
    }
  };

  useEffect(() => {
    fetchSettings();
  }, []);

  return (
    <div className="app-page">
      <Card className="app-card">
        <Typography.Title level={3} style={{ margin: 0 }}>
          系统设置
        </Typography.Title>
        <Typography.Paragraph style={{ marginTop: 8, marginBottom: 0, color: "rgba(15,23,42,0.65)" }}>
          配置系统全局参数
        </Typography.Paragraph>
      </Card>

      <Card className="app-card" style={{ marginTop: 16 }}>
        <Form form={form} layout="vertical" disabled={loading}>
          <Form.Item label="模型训练输出路径" name="training_output_path">
            <Space.Compact style={{ width: "100%" }}>
              <Input placeholder="例如: runs/train" />
              <Button icon={<FolderOpenOutlined />} onClick={selectOutputFolder} title="选择文件夹" />
              <Button type="primary" onClick={() => saveSetting("training_output_path")}>
                保存
              </Button>
            </Space.Compact>
            <div style={{ fontSize: 12, color: "rgba(15,23,42,0.55)", marginTop: 6 }}>
              指定模型训练结果（权重、日志等）的默认保存目录。支持绝对路径或相对路径。
            </div>
          </Form.Item>
        </Form>
      </Card>
    </div>
  );
}
