// ai_image_recognition_frontend/src/components/annotation/ImageGallery.vue
<template>
  <div class="image-gallery">
    <div class="gallery-header">
      <div class="gallery-title-row">
        <h3>已上传的图片 · 共 {{ images.length }} 张，已标注 {{ annotatedCount }} 张</h3>
        <el-select v-model="filterOption" placeholder="筛选" size="small" style="width: 100px;" @change="emitFilter">
          <el-option label="全部" value="all"></el-option>
          <el-option label="已标注" value="annotated"></el-option>
          <el-option label="未标注" value="unannotated"></el-option>
        </el-select>
      </div>
      <div class="selection-controls" v-if="images.length > 0">
        <el-checkbox v-model="selectAll" @change="handleSelectAll">全选</el-checkbox>
        <el-button 
          type="primary" 
          size="small" 
          :disabled="selectedImages.length === 0"
          @click="batchAnnotate"
        >
          批量标注
        </el-button>
        <el-button 
          type="success" 
          size="small" 
          :disabled="selectedImages.length === 0"
          @click="batchExport"
        >
          批量导出
        </el-button>
        <el-button 
          type="warning" 
          size="small" 
          :disabled="selectedImages.length === 0"
          @click="batchClearAnnotations"
        >
          批量清除标注
        </el-button>
        <el-button 
          type="danger" 
          size="small" 
          :disabled="selectedImages.length === 0"
          @click="batchDelete"
        >
          批量删除
        </el-button>
      </div>
    </div>
    <div class="images-grid">
      <div 
        v-for="item in displayedItems" 
        :key="item.index"
        class="image-item"
        :class="{ active: currentIndex === item.index, selected: selectedImages.includes(item.index) }"
        @click="selectImage(item.index, $event)"
      >
        <div class="checkbox-wrapper" @click.stop>
          <el-checkbox v-model="item.image.selected" @change="updateSelection(item.index)"></el-checkbox>
        </div>
        <img :src="item.image.url" :alt="item.image.name" />
        <div class="image-overlay">
          <span class="image-name">{{ item.image.name }}</span>
          <el-button
            v-if="!item.image.isRemote"
            type="danger"
            size="small"
            circle
            @click.stop="removeImage(item.index)"
            class="remove-btn"
          >
            <el-icon><Close /></el-icon>
          </el-button>
        </div>
        <div class="annotation-badge" v-if="getStats(item.index).count > 0">
          <span class="badge-count">{{ getStats(item.index).count }}个框</span>
          <span class="badge-saved" v-if="getStats(item.index).saved">已保存</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue';
import { Close } from '@element-plus/icons-vue';

const props = defineProps({
  images: {
    type: Array,
    default: () => []
  },
  currentIndex: {
    type: Number,
    default: -1
  },
  /** 每张图的标注数量与是否已保存，与 images 索引对应 */
  annotationStats: {
    type: Array,
    default: () => []
  },
  /** 筛选：all / annotated / unannotated */
  filterOption: {
    type: String,
    default: 'all'
  }
});

const emit = defineEmits(['select', 'remove', 'batchAnnotate', 'batchExport', 'batchClearAnnotations', 'batchDelete', 'update:filterOption']);

const filterOption = ref(props.filterOption);
watch(() => props.filterOption, (v) => { filterOption.value = v; });

function getStats(index) {
  const s = props.annotationStats[index];
  return s ? { count: s.count || 0, saved: !!s.saved } : { count: 0, saved: false };
}

const annotatedCount = computed(() => {
  return (props.annotationStats || []).filter(s => s && (s.count || 0) > 0).length;
});

const displayedIndices = computed(() => {
  const stats = props.annotationStats;
  const filter = filterOption.value;
  if (filter === 'all') return props.images.map((_, i) => i);
  return props.images
    .map((_, i) => i)
    .filter(i => {
      const count = (stats[i] && stats[i].count) || 0;
      if (filter === 'annotated') return count > 0;
      if (filter === 'unannotated') return count === 0;
      return true;
    });
});

const displayedItems = computed(() =>
  displayedIndices.value.map(index => ({ index, image: props.images[index] }))
);

function emitFilter() {
  emit('update:filterOption', filterOption.value);
}

// 多选相关状态
const selectedImages = ref([]);
const selectAll = ref(false);

watch(() => props.images, (newImages) => {
  newImages.forEach(image => {
    if (image.selected === undefined) image.selected = false;
  });
}, { immediate: true, deep: true });

const handleSelectAll = (val) => {
  displayedItems.value.forEach(({ index }) => {
    props.images[index].selected = val;
  });
  updateSelectedImages();
};

const updateSelection = (index) => {
  updateSelectedImages();
  selectAll.value = displayedItems.value.length > 0 && displayedItems.value.every(item => props.images[item.index].selected);
};

const updateSelectedImages = () => {
  selectedImages.value = props.images
    .map((image, index) => image.selected ? index : -1)
    .filter(index => index !== -1);
};

const selectImage = (index, event) => {
  if (event && event.ctrlKey) {
    props.images[index].selected = !props.images[index].selected;
    updateSelection(index);
  } else {
    emit('select', index);
  }
};

const removeImage = (index) => {
  emit('remove', index);
  updateSelectedImages();
};

// 批量标注
const batchAnnotate = () => {
  emit('batchAnnotate', selectedImages.value);
};

// 批量导出
const batchExport = () => {
  emit('batchExport', selectedImages.value);
};

// 批量清除标注
const batchClearAnnotations = () => {
  emit('batchClearAnnotations', selectedImages.value);
};

// 批量删除
const batchDelete = () => {
  emit('batchDelete', selectedImages.value);
};

// 供父组件（如智能体增广）获取当前选中的图片索引
defineExpose({
  getSelectedIndices() {
    return selectedImages.value;
  }
});
</script>

<style scoped>
.image-gallery {
  padding: 10px;
  height: auto;
  max-height: 300px;
  overflow-y: auto;
}

.gallery-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}

.selection-controls {
  display: flex;
  align-items: center;
  gap: 10px;
}

.images-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
  gap: 15px;
  margin-top: 10px;
}

.image-item {
  position: relative;
  border-radius: 4px;
  overflow: hidden;
  cursor: pointer;
  border: 2px solid transparent;
  transition: all 0.3s;
}

.image-item.active {
  border-color: #409EFF;
  box-shadow: 0 0 8px rgba(64, 158, 255, 0.6);
}

.image-item.selected {
  border-color: #67C23A;
  box-shadow: 0 0 8px rgba(103, 194, 58, 0.6);
}

.image-item.active.selected {
  border-color: #E6A23C;
  box-shadow: 0 0 8px rgba(230, 162, 60, 0.6);
}

.checkbox-wrapper {
  position: absolute;
  top: 5px;
  left: 5px;
  z-index: 10;
  background-color: rgba(255, 255, 255, 0.7);
  border-radius: 3px;
  padding: 2px;
}

.image-item img {
  width: 100%;
  height: 120px;
  object-fit: cover;
  display: block;
}

.image-overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.6);
  color: white;
  padding: 4px;
  font-size: 12px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.image-name {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 70%;
}

.remove-btn {
  padding: 2px;
  height: 20px;
  width: 20px;
}

.gallery-title-row {
  display: flex;
  align-items: center;
  gap: 10px;
}

.annotation-badge {
  position: absolute;
  top: 28px;
  right: 5px;
  z-index: 10;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 2px;
}

.badge-count {
  background: rgba(103, 194, 58, 0.95);
  color: #fff;
  font-size: 11px;
  padding: 2px 6px;
  border-radius: 4px;
}

.badge-saved {
  background: rgba(64, 158, 255, 0.95);
  color: #fff;
  font-size: 10px;
  padding: 1px 4px;
  border-radius: 3px;
}
</style>

// ai_image_recognition_frontend_next/src/components/annotation/ImageGallery.jsx
"use client";

import { Button, Checkbox, Select, Space, Tag } from "antd";
import { CloseOutlined } from "@ant-design/icons";
import { useEffect, useMemo, useState } from "react";

export default function ImageGallery({
  images,
  currentIndex,
  annotationStats,
  filterOption,
  onFilterChange,
  onSelect,
  onRemove,
  onBatchAnnotate,
  onBatchExport,
  onBatchClearAnnotations,
  onBatchDelete,
}) {
  const [selectAll, setSelectAll] = useState(false);
  const [selectedIndices, setSelectedIndices] = useState([]);

  const getStats = (idx) => annotationStats?.[idx] || { count: 0, saved: false };

  const annotatedCount = useMemo(
    () => (annotationStats || []).filter((s) => (s?.count || 0) > 0).length,
    [annotationStats]
  );

  const displayedIndices = useMemo(() => {
    if (!Array.isArray(images)) return [];
    if (filterOption === "annotated") return images.map((_, i) => i).filter((i) => (getStats(i).count || 0) > 0);
    if (filterOption === "unannotated") return images.map((_, i) => i).filter((i) => (getStats(i).count || 0) === 0);
    return images.map((_, i) => i);
  }, [images, filterOption, annotationStats]);

  const displayedItems = useMemo(() => displayedIndices.map((i) => ({ index: i, image: images[i] })), [displayedIndices, images]);

  const updateSelected = () => {
    const sel = (images || []).map((img, i) => (img?.selected ? i : -1)).filter((i) => i >= 0);
    setSelectedIndices(sel);
  };

  useEffect(() => {
    (images || []).forEach((img) => {
      if (img && typeof img.selected === "undefined") img.selected = false;
    });
    updateSelected();
  }, [images]);

  const handleSelectAll = (checked) => {
    displayedItems.forEach(({ index }) => {
      if (images[index]) images[index].selected = checked;
    });
    setSelectAll(checked);
    updateSelected();
  };

  const handleToggleOne = (index, checked) => {
    if (images[index]) images[index].selected = checked;
    updateSelected();
    setSelectAll(displayedItems.length > 0 && displayedItems.every((it) => images[it.index]?.selected));
  };

  const clickItem = (index, e) => {
    if (e?.ctrlKey) {
      const next = !images[index]?.selected;
      handleToggleOne(index, next);
      return;
    }
    onSelect?.(index);
  };

  return (
    <div style={{ padding: 10, maxHeight: 300, overflowY: "auto" }}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
        <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>
          <b>已上传的图片 · 共 {images.length} 张，已标注 {annotatedCount} 张</b>
          <Select
            size="small"
            style={{ width: 120 }}
            value={filterOption}
            onChange={(v) => onFilterChange?.(v)}
            options={[
              { label: "全部", value: "all" },
              { label: "已标注", value: "annotated" },
              { label: "未标注", value: "unannotated" },
            ]}
          />
        </div>

        {images.length ? (
          <Space wrap>
            <Checkbox checked={selectAll} onChange={(e) => handleSelectAll(e.target.checked)}>
              全选
            </Checkbox>
            <Button size="small" type="primary" disabled={!selectedIndices.length} onClick={() => onBatchAnnotate?.(selectedIndices)}>
              批量标注
            </Button>
            <Button size="small" type="primary" ghost disabled={!selectedIndices.length} onClick={() => onBatchExport?.(selectedIndices)}>
              批量导出
            </Button>
            <Button size="small" disabled={!selectedIndices.length} onClick={() => onBatchClearAnnotations?.(selectedIndices)}>
              批量清除标注
            </Button>
            <Button size="small" danger disabled={!selectedIndices.length} onClick={() => onBatchDelete?.(selectedIndices)}>
              批量删除
            </Button>
          </Space>
        ) : null}
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))", gap: 12, marginTop: 12 }}>
        {displayedItems.map(({ index, image }) => {
          const stats = getStats(index);
          const active = index === currentIndex;
          const selected = !!image?.selected;
          return (
            <div
              key={index}
              onClick={(e) => clickItem(index, e)}
              style={{
                position: "relative",
                borderRadius: 10,
                overflow: "hidden",
                cursor: "pointer",
                border: `2px solid ${active && selected ? "#faad14" : active ? "#1677ff" : selected ? "#52c41a" : "transparent"}`,
                boxShadow: active || selected ? "0 10px 20px rgba(15,23,42,0.10)" : "none",
                background: "#fff",
              }}
            >
              <div style={{ position: "absolute", top: 6, left: 6, zIndex: 2, background: "rgba(255,255,255,0.75)", borderRadius: 6, padding: "2px 4px" }}>
                <Checkbox
                  checked={selected}
                  onChange={(e) => handleToggleOne(index, e.target.checked)}
                  onClick={(e) => e.stopPropagation()}
                />
              </div>
              <img
                src={image?.thumbnail || image?.url}
                alt={image?.name}
                style={{ width: "100%", height: 120, objectFit: "cover", display: "block" }}
              />
              <div style={{ position: "absolute", left: 0, right: 0, bottom: 0, padding: 6, background: "rgba(0,0,0,0.55)", color: "#fff", display: "flex", justifyContent: "space-between", gap: 8, alignItems: "center" }}>
                <div style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: 12, maxWidth: "70%" }}>
                  {image?.name}
                </div>
                {!image?.isRemote ? (
                  <Button
                    size="small"
                    danger
                    shape="circle"
                    icon={<CloseOutlined />}
                    onClick={(e) => {
                      e.stopPropagation();
                      onRemove?.(index);
                      updateSelected();
                    }}
                  />
                ) : null}
              </div>
              {stats.count > 0 ? (
                <div style={{ position: "absolute", top: 30, right: 6, zIndex: 2, display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 4 }}>
                  <Tag color="green">{stats.count}个框</Tag>
                  {stats.saved ? <Tag color="blue">已保存</Tag> : null}
                </div>
              ) : null}
            </div>
          );
        })}
      </div>
    </div>
  );
}
